desarrollo_web/src/Entity/Test.php
<?php

namespace App\Entity;

use App\Repository\TestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TestRepository::class)]
class Test
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pocillos_hab = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nombre_alt = null;

    #[ORM\Column(length: 5000, nullable: true)]
    private ?string $descripcion = null;

    #[ORM\ManyToOne(inversedBy: 'tests')]
    private ?Usuario $usuario = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ruta_imagen = null;

    /**
     * @var Collection<int, Pocillo>
     */
    #[ORM\OneToMany(targetEntity: Pocillo::class, mappedBy: 'test', orphanRemoval: true)]
    private Collection $pocillos;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fechaHora = null;

    public function __construct()
    {
        $this->pocillos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPocillosHab(): ?string
    {
        return $this->pocillos_hab;
    }

    public function setPocillosHab(string $pocillos_hab): static
    {
        $this->pocillos_hab = $pocillos_hab;

        return $this;
    }

    public function getNombreAlt(): ?string
    {
        return $this->nombre_alt;
    }

    public function setNombreAlt(?string $nombre_alt): static
    {
        $this->nombre_alt = $nombre_alt;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): static
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * @return Collection<int, pocillo>
     */
    public function getPocillos(): Collection
    {
        return $this->pocillos;
    }

    public function addPocillo(Pocillo $pocillo): static
    {
        if (!$this->pocillos->contains($pocillo)) {
            $this->pocillos->add($pocillo);
            $pocillo->setTest($this);
        }

        return $this;
    }

    public function removePocillo(Pocillo $pocillo): static
    {
        if ($this->pocillos->removeElement($pocillo)) {
            // set the owning side to null (unless already changed)
            if ($pocillo->getTest() === $this) {
                $pocillo->setTest(null);
            }
        }

        return $this;
    }

    public function getFechaHora(): ?\DateTimeInterface
    {
        return $this->fechaHora;
    }

    public function setFechaHora(\DateTimeInterface $fechaHora): static
    {
        $this->fechaHora = $fechaHora;

        return $this;
    }

    public function getRutaImagen(): ?string
    {
        return $this->ruta_imagen;
    }

    public function setRutaImagen(string $rutaImagen): self
    {
        $this->ruta_imagen = $rutaImagen;

        return $this;
    }
}

desarrollo_web/src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UsuarioRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER', fields: ['email'])] 
#[UniqueEntity(
    fields: ['email'],
    message: 'Ya existe un usuario registrado con este correo electrónico.'
)]
class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 8, minMessage: 'La contraseña debe tener al menos {{ limit }} caracteres.')]
    private ?string $password = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private ?string $nombre = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private ?string $apellido = null;


    /**
     * @var Collection<int, Test>
     */
    #[ORM\OneToMany(targetEntity: Test::class, mappedBy: 'usuario')]
    private Collection $tests;

    public function __construct()
    {
        $this->tests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(string $apellido): static
    {
        $this->apellido = $apellido;

        return $this;
    }

    public function getNombreCompleto(): ?string
    {
        return $this->apellido . ', ' . $this->nombre;
    }


    /**
     * @return Collection<int, test>
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Test $test): static
    {
        if (!$this->tests->contains($test)) {
            $this->tests->add($test);
            $test->setUsuario($this);
        }

        return $this;
    }

    public function removeTest(Test $test): static
    {
        if ($this->tests->removeElement($test)) {
            // set the owning side to null (unless already changed)
            if ($test->getUsuario() === $this) {
                $test->setUsuario(null);
            }
        }

        return $this;
    }
}

desarrollo_web/templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ELISATester{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}?v={{ random() }}">
    <script src="{{ asset('js/base.js') }}"></script>
</head>
<body>
    <header>
        <nav class="navbar">
            <span class="menu-btn material-symbols-rounded">menu</span>
            <a href="{{path('app_index')}}" class="logo">
                <img src="{{ asset('images/logo.png') }}" alt="logo" class="logo-img">
                <h2>ELISATester</h2>
            </a>
            <ul class="nav-links">
                <li><a href="{{path('app_index')}}">Inicio</a></li>
                <li><a href="{{path('app_image_upload')}}">Carga</a></li>
                <li><a href="{{ path('app_test_list') }}">Resultados</a></li>
                <li><a href="{{ path('app_contact') }}">Contacto</a></li>
            </ul>
            {% if app.user %}
                <div class="user-menu" id="user-menu">
                    <span id="user-menu-toggle">
                        {{ app.user.nombre }} {{ app.user.apellido }}
                        <span class="material-symbols-rounded">expand_more</span>
                    </span>
                    <ul class="dropdown-menu" id="user-dropdown-menu">
                        <li><a href="{{ path('app_edit_profile') }}">Editar perfil</a></li>
                        <li><a href="{{ path('app_logout') }}">Cerrar sesión</a></li>
                    </ul>
                </div>

            {% else %}
                <button class="login-btn" onclick="window.location.href='{{ path('app_login') }}'">Iniciar Sesión</button>
            {% endif %}
        </nav>
    </header>

    <!-- Aquí va el contenido de la página -->
    <main>
        {% block body %}{% endblock %}
    </main>
</body>
</html>

desarrollo_web/templates/resultado.html.twig
<!DOCTYPE html>
<html>
    <head>
        <style>{{ css|raw }}</style>
    </head>
    <body>
        <div class="row">
            <img src="{{ logoBase64 }}" alt="logo" class="logo-img">
            <h1 class="h1" style="margin-left: 20px; margin-top: 20px;">ELISATester</h1>
        </div>
        <hr>
        <p><strong>Nombre:</strong> {{ test.nombreAlt }}</p>
        <p><strong>Usuario:</strong> {{ test.usuario.nombreCompleto }}</p>
        <p><strong>Fecha y hora de realización:</strong> {{ test.fechaHora|date('d/m/Y H:i') }}</p>
        <p><strong>Descripción:</strong> {{ test.descripcion }}</p>
        <div class="image-container">
            <img src="{{ imagenBase64 }}" alt="Resultado">
        </div>
        <br>
        <table>
            <tr>
                <td><img src="{{ referencias[2] }}" class="ref-container"></td>
                <td><strong>Negativo</strong></td>
            </tr>
            <tr>
                <td><img src="{{ referencias[0] }}" class="ref-container"></td>
                <td><strong>Positivo</strong></td>
            </tr>
            <tr>
                <td><img src="{{ referencias[1] }}" class="ref-container"></td>
                <td>
                    <strong>Posible</strong><br>
                    <span>(volver a testear o verificar con otro método)</span>
                </td>
            </tr>
        </table>
    </body>
</html>